name: Random Daily Commits

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set git
        run: |
          git config user.name "tranquyk2"
          git config user.email "tranquyk2@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Generate random commits
        run: |
          # Random từ 3 -> 9 commit mỗi ngày
          COMMITS=$((RANDOM % 7 + 3))

          echo "Today will make $COMMITS commits"

          for i in $(seq 1 $COMMITS); do
            HOUR=$((RANDOM % 24))
            MIN=$((RANDOM % 60))
            SEC=$((RANDOM % 60))

            DATE=$(date -d "today $HOUR:$MIN:$SEC" +"%Y-%m-%d %H:%M:%S")

            echo "Commit $i at $DATE" >> commit-log.txt
            git add commit-log.txt

            GIT_AUTHOR_DATE="$DATE" \
            GIT_COMMITTER_DATE="$DATE" \
            git commit -m "Daily random commit $i"

          done

      - name: Push
        run: git push
